/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LatihanGUI;

/**
 *
 * @author Tarishaulia
 */
public class BlanganBinner extends javax.swing.JFrame {

    /**
     * Creates new form BlanganBinner
     */
    public BlanganBinner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bd = new javax.swing.JTextField();
        bb = new javax.swing.JTextField();
        ctb = new javax.swing.JButton();
        ctd = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));
        jPanel1.setLayout(null);

        jLabel1.setText("Bilangan Demisal");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(38, 70, 110, 30);

        jLabel2.setText("Bilangan Binner");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 160, 100, 50);
        jPanel1.add(bd);
        bd.setBounds(160, 70, 180, 30);
        jPanel1.add(bb);
        bb.setBounds(160, 170, 190, 30);

        ctb.setText("convert to binner");
        ctb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctbActionPerformed(evt);
            }
        });
        jPanel1.add(ctb);
        ctb.setBounds(40, 120, 150, 30);

        ctd.setText("convert to desimal");
        ctd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctdActionPerformed(evt);
            }
        });
        jPanel1.add(ctd);
        ctd.setBounds(210, 120, 160, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 60, 360, 150);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 420, 260);

        setBounds(0, 0, 431, 303);
    }// </editor-fold>//GEN-END:initComponents

    private void ctbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctbActionPerformed
        // TODO add your handling code here:
        int desi = Integer.valueOf(bd.getText());
         String bin = Integer.toBinaryString(desi);
         bb.setText(bin);
    }//GEN-LAST:event_ctbActionPerformed

    private void ctdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctdActionPerformed
        // TODO add your handling code here:
        String biner = bb.getText();
         int des = Integer.parseInt(biner, 2);
         bd.setText(String.valueOf(des));
    }//GEN-LAST:event_ctdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlanganBinner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlanganBinner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlanganBinner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlanganBinner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlanganBinner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bb;
    private javax.swing.JTextField bd;
    private javax.swing.JButton ctb;
    private javax.swing.JButton ctd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
