/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LatihanGUI;

/**
 *
 * @author Tarishaulia
 */
public class Kuis1 extends javax.swing.JFrame {

    /**
     * Creates new form Kuis1
     */
    public Kuis1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        varnama = new javax.swing.JTextField();
        varkelas = new javax.swing.JTextField();
        varmapel = new javax.swing.JTextField();
        varnilai = new javax.swing.JTextField();
        btnproses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Penilaian Siswa");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 20, 120, 30);

        jLabel2.setText("Nama");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 70, 70, 30);

        jLabel3.setText("Kelas");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 110, 70, 30);

        jLabel4.setText("Mapel");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 150, 70, 30);

        jLabel5.setText("Nilai");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 190, 60, 30);
        jPanel1.add(varnama);
        varnama.setBounds(110, 70, 120, 30);
        jPanel1.add(varkelas);
        varkelas.setBounds(110, 110, 120, 30);
        jPanel1.add(varmapel);
        varmapel.setBounds(110, 150, 120, 30);
        jPanel1.add(varnilai);
        varnilai.setBounds(110, 190, 120, 30);

        btnproses.setText("Proses");
        btnproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosesActionPerformed(evt);
            }
        });
        jPanel1.add(btnproses);
        btnproses.setBounds(90, 230, 73, 30);

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 280, 230, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 280, 400);

        setBounds(0, 0, 292, 439);
    }// </editor-fold>//GEN-END:initComponents

    private void btnprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosesActionPerformed
        // TODO add your handling code here:
        String nama = varnama.getText();
        String kelas = varkelas.getText();
        String mapel = varmapel.getText();
        int nilai = Integer.parseInt(varnilai.getText());
        String keterangan ="";
        
        //untuk keterangan 
      
         if(nilai < 75)
            keterangan ="Tidak Lulus";
        else if(nilai >=75 && nilai < 100)
            keterangan ="Lulus";
        else if(nilai == 100)
            keterangan ="Sempurna";
        else if(nilai > 100)
            keterangan ="Amazing";
        else if(nilai > 110)
            keterangan ="Error!";
        
        area.setText("Nama Siswa : "+nama+"\n"+"Kelas : "+kelas+"\n"+"Mapel : "
                +mapel+"\n"+"Nilai : "+nilai+"\n Keterangan :"+keterangan);
    }//GEN-LAST:event_btnprosesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kuis1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton btnproses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField varkelas;
    private javax.swing.JTextField varmapel;
    private javax.swing.JTextField varnama;
    private javax.swing.JTextField varnilai;
    // End of variables declaration//GEN-END:variables
}
