/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LatihanGUI;

/**
 *
 * @author Tarishaulia
 */
public class Latihan2 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan2
     */
    public Latihan2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pilihanjurusan = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        varNama = new javax.swing.JTextField();
        varAbsen = new javax.swing.JTextField();
        rdbTkj = new javax.swing.JRadioButton();
        rdbRpl = new javax.swing.JRadioButton();
        cbProgram = new javax.swing.JCheckBox();
        cbAnimator = new javax.swing.JCheckBox();
        cbDesigner = new javax.swing.JCheckBox();
        cbVideoediting = new javax.swing.JCheckBox();
        buttonSubmit = new javax.swing.JButton();
        buttonRemove = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 255));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setText("BIODATA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 10, 70, 30);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 64, 50, 20);

        jLabel3.setText("Absen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 100, 50, 30);

        jLabel4.setText("Jurusan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 130, 60, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Hobi");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 170, 50, 30);

        varNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varNamaActionPerformed(evt);
            }
        });
        getContentPane().add(varNama);
        varNama.setBounds(100, 60, 210, 30);
        getContentPane().add(varAbsen);
        varAbsen.setBounds(100, 100, 210, 30);

        Pilihanjurusan.add(rdbTkj);
        rdbTkj.setText("TKJ");
        rdbTkj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTkjActionPerformed(evt);
            }
        });
        getContentPane().add(rdbTkj);
        rdbTkj.setBounds(90, 137, 70, 23);

        Pilihanjurusan.add(rdbRpl);
        rdbRpl.setText("RPL");
        getContentPane().add(rdbRpl);
        rdbRpl.setBounds(200, 137, 70, 23);

        cbProgram.setText("Programming");
        getContentPane().add(cbProgram);
        cbProgram.setBounds(90, 170, 120, 30);

        cbAnimator.setText("Animator");
        getContentPane().add(cbAnimator);
        cbAnimator.setBounds(230, 170, 110, 30);

        cbDesigner.setText("Designer");
        getContentPane().add(cbDesigner);
        cbDesigner.setBounds(90, 200, 120, 30);

        cbVideoediting.setText("Video Editing");
        getContentPane().add(cbVideoediting);
        cbVideoediting.setBounds(230, 200, 150, 30);

        buttonSubmit.setText("Submit");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSubmit);
        buttonSubmit.setBounds(30, 230, 100, 23);

        buttonRemove.setText("Remove");
        buttonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(buttonRemove);
        buttonRemove.setBounds(140, 230, 100, 23);

        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });
        getContentPane().add(buttonExit);
        buttonExit.setBounds(250, 230, 100, 23);

        jLabel6.setText("Hasil");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 270, 60, 14);

        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane1.setViewportView(hasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 290, 250, 96);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 50, 380, 110);

        setBounds(0, 0, 486, 465);
    }// </editor-fold>//GEN-END:initComponents

    private void rdbTkjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTkjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbTkjActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        // TODO add your handling code here:
        dispose();
        //System.exit(1);
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveActionPerformed
        // TODO add your handling code here:
        varNama.setText("");
        varAbsen.setText("");
        Pilihanjurusan.clearSelection();
        hasil.setText("");
        cbProgram.setSelected(false);
        cbAnimator.setSelected(false);
        cbVideoediting.setSelected(false);
        cbDesigner.setSelected(false);
    }//GEN-LAST:event_buttonRemoveActionPerformed

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        // TODO add your handling code here:
        String nama = varNama.getText();
        String absen = varAbsen.getText();
        String jurusan;
        String hobi="";
        
        //untuk pilihan jurusan
        if (rdbRpl.isSelected())
            jurusan="RPL";
        else if (rdbTkj.isSelected())
            jurusan="TKJ";
        else
            jurusan=" ";
        
        //untuk pilihan checkbox
        if (cbAnimator.isSelected())
            hobi+=cbAnimator.getText()+", ";
        if (cbDesigner.isSelected())
            hobi+=cbDesigner.getText()+", ";
        if (cbProgram.isSelected())
            hobi+=cbProgram.getText()+", ";
        if (cbVideoediting.isSelected())
            hobi+=cbVideoediting.getText()+", ";
        
        //untuk hasil
        hasil.setText(" Nama anda : "+nama+"\n Absen anda : "+absen+"\n Jurusan anda : "+jurusan+"\n Hobi anda : "+hobi);
    }//GEN-LAST:event_buttonSubmitActionPerformed

    private void varNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varNamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Pilihanjurusan;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonRemove;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JCheckBox cbAnimator;
    private javax.swing.JCheckBox cbDesigner;
    private javax.swing.JCheckBox cbProgram;
    private javax.swing.JCheckBox cbVideoediting;
    private javax.swing.JTextArea hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbRpl;
    private javax.swing.JRadioButton rdbTkj;
    private javax.swing.JTextField varAbsen;
    private javax.swing.JTextField varNama;
    // End of variables declaration//GEN-END:variables
}
