/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LatihanGUI;

/**
 *
 * @author Tarishaulia
 */
public class Latihan6 extends javax.swing.JFrame {
        String angka;
        double jumlah,angka1,angka2;
        int pilih;
    /**
     * Creates new form Latihan6
     */
    public Latihan6() {
               initComponents();
               angka = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        display = new javax.swing.JTextField();
        buttonHapus = new javax.swing.JButton();
        buttonCE = new javax.swing.JButton();
        buttonC = new javax.swing.JButton();
        buttonKuranglebih = new javax.swing.JButton();
        buttonAkar = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        buttonBagi = new javax.swing.JButton();
        buttonPersen = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        buttonKali = new javax.swing.JButton();
        button1bagix = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        buttonKurang = new javax.swing.JButton();
        buttonSamadengan = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        buttonKoma = new javax.swing.JButton();
        buttonTambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        display.setEditable(false);
        display.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        jPanel1.add(display);
        display.setBounds(20, 20, 380, 100);

        buttonHapus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buttonHapus.setText("←");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });
        jPanel1.add(buttonHapus);
        buttonHapus.setBounds(20, 130, 60, 50);

        buttonCE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonCE.setText("CE");
        buttonCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCEActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCE);
        buttonCE.setBounds(100, 130, 60, 50);

        buttonC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonC.setText("C");
        buttonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCActionPerformed(evt);
            }
        });
        jPanel1.add(buttonC);
        buttonC.setBounds(180, 130, 60, 50);

        buttonKuranglebih.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonKuranglebih.setText("±");
        buttonKuranglebih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKuranglebihActionPerformed(evt);
            }
        });
        jPanel1.add(buttonKuranglebih);
        buttonKuranglebih.setBounds(260, 130, 60, 50);

        buttonAkar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonAkar.setText("√");
        buttonAkar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAkarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAkar);
        buttonAkar.setBounds(340, 130, 60, 50);

        button7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button7.setText("7");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        jPanel1.add(button7);
        button7.setBounds(20, 190, 60, 50);

        button8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button8.setText("8");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        jPanel1.add(button8);
        button8.setBounds(100, 190, 60, 50);

        button9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button9.setText("9");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        jPanel1.add(button9);
        button9.setBounds(180, 190, 60, 50);

        buttonBagi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonBagi.setText("/");
        buttonBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBagiActionPerformed(evt);
            }
        });
        jPanel1.add(buttonBagi);
        buttonBagi.setBounds(260, 190, 60, 50);

        buttonPersen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonPersen.setText("%");
        buttonPersen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPersenActionPerformed(evt);
            }
        });
        jPanel1.add(buttonPersen);
        buttonPersen.setBounds(340, 190, 60, 50);

        button4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button4.setText("4");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        jPanel1.add(button4);
        button4.setBounds(20, 250, 60, 50);

        button1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button1.setText("1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1);
        button1.setBounds(20, 310, 60, 50);

        button5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button5.setText("5");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        jPanel1.add(button5);
        button5.setBounds(100, 250, 60, 50);

        button6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button6.setText("6");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        jPanel1.add(button6);
        button6.setBounds(180, 250, 60, 50);

        buttonKali.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonKali.setText("X");
        buttonKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKaliActionPerformed(evt);
            }
        });
        jPanel1.add(buttonKali);
        buttonKali.setBounds(260, 250, 60, 50);

        button1bagix.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button1bagix.setText("1/x");
        button1bagix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1bagixActionPerformed(evt);
            }
        });
        jPanel1.add(button1bagix);
        button1bagix.setBounds(340, 250, 60, 50);

        button2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button2.setText("2");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2);
        button2.setBounds(100, 310, 60, 50);

        button3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button3.setText("3");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        jPanel1.add(button3);
        button3.setBounds(180, 310, 60, 50);

        buttonKurang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonKurang.setText("-");
        buttonKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKurangActionPerformed(evt);
            }
        });
        jPanel1.add(buttonKurang);
        buttonKurang.setBounds(260, 310, 60, 50);

        buttonSamadengan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonSamadengan.setText("=");
        buttonSamadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSamadenganActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSamadengan);
        buttonSamadengan.setBounds(340, 310, 60, 120);

        button0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button0.setText("0");
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });
        jPanel1.add(button0);
        button0.setBounds(20, 370, 140, 60);

        buttonKoma.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonKoma.setText(",");
        buttonKoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKomaActionPerformed(evt);
            }
        });
        jPanel1.add(buttonKoma);
        buttonKoma.setBounds(180, 370, 60, 60);

        buttonTambah.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonTambah.setText("+");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });
        jPanel1.add(buttonTambah);
        buttonTambah.setBounds(260, 370, 60, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 430, 450);

        setBounds(0, 0, 442, 489);
    }// </editor-fold>//GEN-END:initComponents

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        angka +="3";
        display.setText(angka);
    }//GEN-LAST:event_button3ActionPerformed

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("+");
        angka="";
        pilih=1;
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonKomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKomaActionPerformed
        // TODO add your handling code here:
        angka += ",";
        display.setText(angka);
    }//GEN-LAST:event_buttonKomaActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        angka +="1";
        display.setText(angka);
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        angka +="2";
        display.setText(angka);
    }//GEN-LAST:event_button2ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        angka +="4";
        display.setText(angka);
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
        angka +="5";
        display.setText(angka);
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
        angka +="6";
        display.setText(angka);
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
        angka +="7";
        display.setText(angka);
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        // TODO add your handling code here:
        angka +="8";
        display.setText(angka);
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        // TODO add your handling code here:
       angka +="9";
       display.setText(angka);
    }//GEN-LAST:event_button9ActionPerformed

    private void buttonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCActionPerformed
        // TODO add your handling code here:
        display.setText("");
        angka1 = 0.0;
        angka2 = 0.0;
        jumlah = 0.0;
        angka = "";
    }//GEN-LAST:event_buttonCActionPerformed

    private void buttonKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKurangActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("-");
        angka="";
        pilih=2;
    }//GEN-LAST:event_buttonKurangActionPerformed

    private void buttonKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKaliActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("x");
        angka="";
        pilih=3;
    }//GEN-LAST:event_buttonKaliActionPerformed

    private void buttonBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBagiActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("/");
        angka="";
        pilih=4;
        
    }//GEN-LAST:event_buttonBagiActionPerformed

    private void buttonSamadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSamadenganActionPerformed
        // TODO add your handling code here:
        switch (pilih) {
  case 1:
      angka2 = Double.parseDouble(angka);
      jumlah = angka1 + angka2;
      angka = Double.toString(jumlah);
      display.setText(angka);
      break;
  case 2:
      angka2 = Double.parseDouble(angka);
      jumlah = angka1 - angka2;
      angka = Double.toString(jumlah);
      display.setText(angka);
      break;
   case 3:
      angka2 = Double.parseDouble(angka);
      jumlah = angka1 * angka2;
      angka = Double.toString(jumlah);
      display.setText(angka);
      break;
   case 4:
      angka2 = Double.parseDouble(angka);
      jumlah = angka1 / angka2;
      angka = Double.toString(jumlah);
      display.setText(angka);
      break;
   case 5:
       angka2 = Double.parseDouble(angka);
       jumlah = angka1*angka2/100;
       angka = Double.toString(jumlah);
       display.setText(angka); 
       break;
   case 6:
      jumlah = 1/angka1;
      angka = Double.toString(jumlah);
      display.setText(angka);
      break;
   case 7:
       angka2 =Double.parseDouble(angka);
       jumlah = Math.sqrt(angka1);
       angka = Double.toString(jumlah);
       display.setText(angka);
      break;
   case 8 :
       angka2 = Double.parseDouble(angka);
       jumlah = angka1 - angka2;
       angka = Double.toString(jumlah);
       display.setText("-"+angka);
       break;
      default:
      break;
 }
    }//GEN-LAST:event_buttonSamadenganActionPerformed

    private void buttonCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCEActionPerformed
        // TODO add your handling code here:
        display.setText("");
        angka1=0.0;
        angka2=0.0;
        jumlah=0.0;
        angka="";
        
    }//GEN-LAST:event_buttonCEActionPerformed

    private void buttonPersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPersenActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("%");
        angka="";
        pilih=5;
    }//GEN-LAST:event_buttonPersenActionPerformed

    private void button1bagixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1bagixActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("1/x");
        angka="";
        pilih=6;
    }//GEN-LAST:event_button1bagixActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        // TODO add your handling code here:
        angka +="0";
        display.setText(angka);
    }//GEN-LAST:event_button0ActionPerformed

    private void buttonAkarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAkarActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("√");
        angka="";
        pilih=7;
    }//GEN-LAST:event_buttonAkarActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
           angka = angka.substring(0,angka.length()-1);
           display.setText(angka);
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonKuranglebihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKuranglebihActionPerformed
        // TODO add your handling code here:
        if(!angka.contains("-"))
            angka = "-" +angka;
        else
            angka = angka.substring(1, angka.length());
        display.setText(angka);
        pilih = 8;
    }//GEN-LAST:event_buttonKuranglebihActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button1bagix;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonAkar;
    private javax.swing.JButton buttonBagi;
    private javax.swing.JButton buttonC;
    private javax.swing.JButton buttonCE;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonKali;
    private javax.swing.JButton buttonKoma;
    private javax.swing.JButton buttonKurang;
    private javax.swing.JButton buttonKuranglebih;
    private javax.swing.JButton buttonPersen;
    private javax.swing.JButton buttonSamadengan;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JTextField display;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
