/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LatihanGUI;

/**
 *
 * @author Tarishaulia
 */
public class Latihan5 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan5
     */
    //Konstruktor class dengan diisi parameter
    public Latihan5(String nama, String absen, String jurusan, String alamat, String kelas) {
        initComponents();
        Nama.setText(nama);
        Absen.setText(absen);
        Kelas.setText(kelas);
        Jurusan.setText(jurusan);
        Alamat.setText(alamat);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        Absen = new javax.swing.JLabel();
        Kelas = new javax.swing.JLabel();
        Jurusan = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HASIL BIODATA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 24, 180, 20);

        Nama.setForeground(new java.awt.Color(255, 255, 255));
        Nama.setText("NAMA");
        jPanel1.add(Nama);
        Nama.setBounds(40, 94, 220, 20);

        Absen.setForeground(new java.awt.Color(255, 255, 255));
        Absen.setText("ABSEN");
        jPanel1.add(Absen);
        Absen.setBounds(40, 124, 140, 20);

        Kelas.setForeground(new java.awt.Color(255, 255, 255));
        Kelas.setText("KELAS");
        jPanel1.add(Kelas);
        Kelas.setBounds(40, 154, 140, 20);

        Jurusan.setForeground(new java.awt.Color(255, 255, 255));
        Jurusan.setText("JURUSAN");
        jPanel1.add(Jurusan);
        Jurusan.setBounds(40, 184, 160, 20);

        Alamat.setForeground(new java.awt.Color(255, 255, 255));
        Alamat.setText("ALAMAT");
        jPanel1.add(Alamat);
        Alamat.setBounds(40, 214, 150, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 370, 290);

        setBounds(0, 0, 385, 331);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               //
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Absen;
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel Jurusan;
    private javax.swing.JLabel Kelas;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
