/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LatihanGUI;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tarishaulia
 */
public class TabelBiodata extends javax.swing.JFrame {

    /**
     * Creates new form TabelBiodata
     */
    public TabelBiodata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        varnama = new javax.swing.JTextField();
        varalamat = new javax.swing.JTextField();
        varsekolah = new javax.swing.JTextField();
        buttonAdd = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        combo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setText("TABEL BIODATA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 20, 120, 14);

        jLabel2.setText("Nama");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 60, 50, 30);

        jLabel3.setText("Kelas");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 100, 50, 30);

        jLabel4.setText("Alamat");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 140, 50, 30);

        jLabel5.setText("Sekolah");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 180, 60, 30);

        varnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varnamaActionPerformed(evt);
            }
        });
        jPanel1.add(varnama);
        varnama.setBounds(100, 60, 220, 30);

        varalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varalamatActionPerformed(evt);
            }
        });
        jPanel1.add(varalamat);
        varalamat.setBounds(100, 140, 220, 30);
        jPanel1.add(varsekolah);
        varsekolah.setBounds(100, 180, 220, 30);

        buttonAdd.setText("Add");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAdd);
        buttonAdd.setBounds(110, 220, 51, 23);

        buttonExit.setText("Exit");
        jPanel1.add(buttonExit);
        buttonExit.setBounds(210, 220, 51, 23);

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X RPL 1", "X RPL 2", "X RPL 3", "X RPL 4", "X RPL 5", "X RPL 6", "X RPL 7", "X TKJ 1", "X TKJ 2", "X TKJ 3", "X TKJ 4", "X TKJ 5", "X TKJ 6" }));
        jPanel1.add(combo);
        combo.setBounds(100, 100, 80, 30);

        jTable1.setBackground(new java.awt.Color(255, 255, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Kelas", "Alamat", "Sekolah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 270, 340, 90);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 400);

        setBounds(0, 0, 414, 438);
    }// </editor-fold>//GEN-END:initComponents

    private void varnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varnamaActionPerformed

    private void varalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varalamatActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:
        String nama = varnama.getText();
        String kelas = combo.getSelectedItem().toString();
        String alamat = varalamat.getText();
        String sekolah = varsekolah.getText();
        //untuk combobox
        if (combo.getSelectedItem()== "X RPL1"){
        }if (combo.getSelectedItem()== "X RPL2"){
        }if (combo.getSelectedItem()== "X RPL3"){
        }if (combo.getSelectedItem()== "X RPL4"){
        }if (combo.getSelectedItem()== "X RPL5"){
        }if (combo.getSelectedItem()== "X RPL6"){
        }if (combo.getSelectedItem()== "X TKJ1"){
        }if (combo.getSelectedItem()== "X TKJ2"){
        }if (combo.getSelectedItem()== "X TKJ3"){
        }if (combo.getSelectedItem()== "X TKJ4"){
        }if (combo.getSelectedItem()== "X TKJ5"){
        }if (combo.getSelectedItem()== "X TKJ6");
        // untuk tabel
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{varnama.getText(),combo.getSelectedItem(),varalamat.getText(),varsekolah.getText()});
    }//GEN-LAST:event_buttonAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelBiodata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonExit;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField varalamat;
    private javax.swing.JTextField varnama;
    private javax.swing.JTextField varsekolah;
    // End of variables declaration//GEN-END:variables
}
