/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LatihanGUI;

import javax.swing.JOptionPane;

/**
 *
 * @author Tarishaulia
 */
public class VolumeBangunRuang extends javax.swing.JFrame {

    /**
     * Creates new form VolumeBangunRuang
     */
    public VolumeBangunRuang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panjangblk = new javax.swing.JTextField();
        lebarblk = new javax.swing.JTextField();
        tinggiblk = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnbalok = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        sisikbs = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnkubus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jaribola = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnbola = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(null);

        jLabel2.setText("Masukkan Panjang    :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 30, 130, 30);

        jLabel3.setText("Masukkan Lebar        :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 70, 130, 30);

        jLabel4.setText("Masukkan Tinggi        :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 110, 130, 30);

        panjangblk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panjangblkActionPerformed(evt);
            }
        });
        jPanel1.add(panjangblk);
        panjangblk.setBounds(160, 30, 130, 30);
        jPanel1.add(lebarblk);
        lebarblk.setBounds(160, 70, 130, 30);

        tinggiblk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggiblkActionPerformed(evt);
            }
        });
        jPanel1.add(tinggiblk);
        tinggiblk.setBounds(160, 110, 130, 30);

        jLabel5.setText("cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(310, 30, 40, 30);

        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(310, 70, 40, 30);

        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(310, 110, 40, 30);

        btnbalok.setText("Hitung");
        btnbalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbalokActionPerformed(evt);
            }
        });
        jPanel1.add(btnbalok);
        btnbalok.setBounds(170, 170, 110, 30);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(null);

        jLabel8.setText("MASUKKAN PANJANG SISI");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(21, 29, 160, 30);
        jPanel2.add(sisikbs);
        sisikbs.setBounds(20, 70, 80, 40);

        jLabel9.setText("CM");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(110, 70, 60, 40);

        btnkubus.setText("VOLUME");
        btnkubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkubusActionPerformed(evt);
            }
        });
        jPanel2.add(btnkubus);
        btnkubus.setBounds(20, 130, 80, 30);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setLayout(null);

        jLabel10.setText("MASUKKAN PANJANG JARI JARI");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(24, 33, 180, 30);
        jPanel3.add(jaribola);
        jaribola.setBounds(20, 70, 120, 40);

        jLabel11.setText("CM");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(160, 70, 50, 40);

        btnbola.setText("VOLUME");
        btnbola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbolaActionPerformed(evt);
            }
        });
        jPanel3.add(btnbola);
        btnbola.setBounds(20, 130, 100, 40);

        jTabbedPane1.addTab("Bola", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 50, 410, 250);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("PROGRAM PENCARI VOLUME BANGUN RUANG");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 390, 20);

        setBounds(0, 0, 480, 383);
    }// </editor-fold>//GEN-END:initComponents

    private void tinggiblkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggiblkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggiblkActionPerformed

    private void panjangblkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panjangblkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panjangblkActionPerformed

    private void btnbalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbalokActionPerformed
        // TODO add your handling code here:
        int panjang, lebar, tinggi;
        panjang = Integer.parseInt(panjangblk.getText());
        lebar = Integer.parseInt(lebarblk.getText());
        tinggi = Integer.parseInt(tinggiblk.getText());
        int hasil=panjang*lebar*tinggi;
        try{
            JOptionPane.showMessageDialog(null,"Volume Balok Adalah : "+hasil,"luas",JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnbalokActionPerformed

    private void btnkubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkubusActionPerformed
        // TODO add your handling code here:
        int sisi;
        sisi = Integer.parseInt(sisikbs.getText());
        int hasil = sisi*sisi*sisi;
        
        try{
            JOptionPane.showMessageDialog(null,"Volume Kubus Adalah "+hasil,"luas",JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnkubusActionPerformed

    private void btnbolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbolaActionPerformed
        // TODO add your handling code here:
        float jari;
        jari = Integer.parseInt(jaribola.getText());
        float hasil =(float) (4/3*3.14*jari*jari*jari);
        try{
            JOptionPane.showMessageDialog(null,"Volume Bola Adalah "+hasil,"luas",JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error","Gagal",JOptionPane.WARNING_MESSAGE);
        }     
    }//GEN-LAST:event_btnbolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VolumeBangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VolumeBangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VolumeBangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VolumeBangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VolumeBangunRuang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbalok;
    private javax.swing.JButton btnbola;
    private javax.swing.JButton btnkubus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jaribola;
    private javax.swing.JTextField lebarblk;
    private javax.swing.JTextField panjangblk;
    private javax.swing.JTextField sisikbs;
    private javax.swing.JTextField tinggiblk;
    // End of variables declaration//GEN-END:variables
}
